<section>
    <p class="text-right"><a href="addUser.php" class="btn btn-primary"><i class="icon-user-plus"></i> Ajouter un utilisateur</a></p>
    <table id="tableDonnee" class="table">
        <thead>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Email</th>
            <th>Rôle</th>
            <th>Actif</th>
            <th></th>
        </thead>
        <tbody>
            <?php foreach($users as $user):?>
                <tr>
                    <td><?=$user['u_firstname']?></td>
                    <td><?=$user['u_lastname']?></td>
                    <td><?=$user['u_email']?></td>
                    <td><?=ROLES[$user['u_role']]?></td>
                    <td><span class="d-none"><?=$user['u_valide']?></span><a href="publishUser.php?id=<?=$user['u_id']?>"><i class="big <?php if($user['u_valide']==true):?>green icon-toggle-right<?php else:?>red icon-toggle-left<?php endif;?>"></i></a></td>
                    <td><a href="editUser.php?id=<?=$user['u_id']?>"><i class="icon-edit"></i></a> <a href="delUser.php?id=<?=$user['u_id']?>" data-toggle="modal" data-target="#delete"><i class="icon-trash"></i></a></td>
                </tr> 
            <?php endforeach;?>
        </tbody>
    </table>
</section>