<form action="<?php if(is_null($id)):?>addUser.php<?php else:?>editUser.php<?php endif;?>" method="POST" enctype="multipart/form-data">
  <?php if(isset($errorForm) && count($errorForm)>0):?>
    <div class="alert alert-danger" role="alert">
      <ul>
        <?php foreach($errorForm as $error):?>
          <li class="erreur"><?=$error;?></li>
        <?php endforeach;?>
    </div>
  <?php endif;?>
    
  <?php if(!is_null($id)):?>
    <input type="hidden" value="<?=$id?>" name="id">
  <?php endif;?>

  <fieldset>
    <div class="form-group">
      <label for="firstname">Prénom</label>
      <input type="text" class="form-control" id="firstname" name="firstname" value="<?=$firstnameUser?>">
      <small id="titleHelp" class="form-text text-muted">Saisissez le prénom de l'utilisateur</small>
    </div>
    <div class="form-group">
      <label for="lastname">Nom</label>
      <input type="text" class="form-control" id="lastname" name="lastname" value="<?=$lastnameUser?>">
      <small id="titleHelp" class="form-text text-muted">Saisissez le nom de l'utilisateur</small>
    </div>
    <div class="form-group">
      <label for="email">Email</label>
      <input type="email" class="form-control" id="email" name="email" value="<?=$emailUser?>">
      <small id="titleHelp" class="form-text text-muted">Saisissez l'email de l'utilisateur</small>
    </div>
    <div class="form-group">
      <label for="password">Mot de passe <span class="badge badge-light">Au moins 8 caractères</span></label>
      <?php if(!is_null($id)):?><div class="alert alert-dismissible alert-warning">Laissez vide pour ne pas modifier le mot de passe !</div><?php endif;?>

      <div class="row">
        <div class="col-6">
          <input type="password" class="form-control" id="password" name="password" placeholder="Mot de passe">
        </div>
        <div class="col-6">
          <input type="password" class="form-control" id="passwordConf" name="passwordConf" placeholder="Confirmez le mot de passe">
        </div>
      </div>
    </div>
    <div class="form-group">
      <label for="role">Rôle</label>
      <select class="form-control" id="role" name="role">
        <?php foreach(ROLES as $role=>$nameRole):?>
          <option value="<?=$role?>" <?php if($role == $roleUser):?>selected<?php endif;?>><?=$nameRole?></option>
        <?php endforeach;?>
      </select>
       <small id="catHelp" class="form-text text-muted">Sélectionnez un role pour l'utilisateur</small>
    </div>
    <div class="form-group">
      <div class="custom-control custom-switch">
<input type="checkbox" class="custom-control-input" name="valide"  id="valide" <?php if($valideUser == true):?>checked=""<?php endif;?>>
        <label class="custom-control-label" for="valide">Activer l'utilisateur</label>
        <small id="publieHelp" class="form-text text-muted">L'utilisateur ne pourra pas se loguer si vous désactivez cette option !</small>
      </div>
    </div>
    <a href="listeUser.php" class="btn btn-outline-primary">Annuler</a>
    <button type="submit" class="btn btn-primary"><?php if(is_null($id)):?>Créer l'utilisateur<?php else:?>Modifier l'utilisateur<?php endif;?></button>
  </fieldset>
</form>
