<section>
    <!--<p class="text-right"><a href="addArticle.php" class="btn btn-primary"><i class="icon-plus-square"></i> Ajouter un commentaire</a></p>-->
    <table id="tableDonnee" class="table">
        <thead>
            <th>Nom</th>
            <th>Email</th>
            <th>Date publication</th>
            <th>Article</th>
            <th>Publié</th>
            <th>Commentaire</th>
            <th></th>
        </thead>
        <tbody>
            <?php foreach($comments as $comment):?>
                <tr>
                    <td><?=$comment['com_pseudo']?></td>
                    <td><a href="mailto:<?=$comment['com_email']?>"><?=$comment['com_email']?></a></td>
                    <td><?=(new DateTime($comment['com_date_posted']))->format('d/m/Y H:i:s')?></td>
                    <td><span class="badge badge-pill badge-success"><?=$comment['art_title']?></span></td>
                    <td><span class="d-none"><?=$comment['com_valide']?></span><a href="publishComment.php?id=<?=$comment['com_id']?>"><i class="big <?php if($comment['com_valide']==true):?>green icon-toggle-right<?php else:?>red icon-toggle-left<?php endif;?>"></i></a></td>
                    <td><?=htmlentities($comment['com_content'])?></td>
                    <td><!--<a href="editComment.php?id=<?=$comment['com_id']?>"><i class="icon-edit"></i></a> --><a href="delComment.php?id=<?=$comment['art_id']?>" data-toggle="modal" data-target="#delete"><i class="icon-trash"></i></a></td>
                </tr> 
            <?php endforeach;?>
        </tbody>
    </table>
</section>